// Firebase configuration for the ClaimTrek project (claimtrek-e4572).
//
// Normally generated by `flutterfire configure`. Written by hand here from the values in the
// Firebase console, because the Firebase CLI cannot authenticate in this environment. The
// Android values are the same ones in android/app/google-services.json — if you later run
// `flutterfire configure`, it will overwrite this file, which is fine.
//
// These keys are not secrets. An Android API key is restricted by package name and signing
// certificate, so it is useless to anyone without the app's signing key; the real access
// control lives in firestore.rules.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured. Register a Web app in the Firebase console and add its '
        'options here — the Android values below will not work in a browser.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'ClaimTrek is only configured for Android. Register a $defaultTargetPlatform app '
          'in the Firebase console to add it.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWQVhy1xfQ2zkKqMz1ibw5M7_EsSXS6o',
    appId: '1:452033087173:android:ed9ede4f0a5cca59af12ac',
    messagingSenderId: '452033087173',
    projectId: 'claimtrek-e4572',
    storageBucket: 'claimtrek-e4572.firebasestorage.app',
  );
}
